# Generated by Django 3.2.9 on 2022-01-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Date',
            new_name='date',
        ),
    ]
